services:
  legolas-n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: legolas-n8n
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      GENERIC_TIMEZONE: America/Sao_Paulo

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: legolas-db-n8n
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_SCHEMA: public

      QUEUE_MODE: redis
      QUEUE_REDIS_HOST: legolas-redis-n8n
      QUEUE_REDIS_PORT: 6379

      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_HOST: 
      N8N_PROTOCOL: https
      WEBHOOK_URL:


    volumes:
      - /opt/docker/legolas-n8n/n8n-data:/home/node/.n8n

    depends_on:
      - legolas-db-n8n
      - legolas-redis-n8n

    networks:
      - radagast_net


  legolas-db-n8n:
    image: postgres:15-alpine
    container_name: legolas-db-n8n
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - /opt/docker/legolas-n8n/postgres-data:/var/lib/postgresql/data

    networks:
      - radagast_net


  legolas-redis-n8n:
    image: redis:7-alpine
    container_name: legolas-redis-n8n
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - /opt/docker/legolas-n8n/redis-data:/data

    networks:
      - radagast_net


networks:
  radagast_net:
    external: true
